### ISSUE TITLE
issues with wget command and reinstalling Conda environment

### ISSUE THREAD

**Issue by stephaniehall123** [biostars/biostar-handbook-issues#144]
Hello, 
I'm currently trying to work through the newest course. I set up my unix environment last year but then I got busy and didn't have time to follow through with the course. Now I'm trying to find time and continue to work through the course.

One of the issues that I have run into is the wget command is coming up not found (see below). I tried using the curl command but it doesn't seem to download it, it just shows me what's in it.

$ wget http://purl.obolibrary.org/obo/go.obo
-bash: wget: command not found
(base) 

I then went to your "how to fix problems" section to see if there was something in there and so I decided to reinstall by removing the previous environment by using the commands: 

conda create -y --name bioinfo python=3.6
conda activate bioinfo
curl http://data.biostarhandbook.com/install/conda.txt | xargs conda install -y
conda create -y --name bioinfo python=3.6

Collecting package metadata (current_repodata.json): failed
WARNING conda.exceptions:print_unexpected_error_report(1213): KeyError('pkgs_dirs')
Traceback (most recent call last):
  File "/Users/stephaniehall/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "/Users/stephaniehall/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/Users/stephaniehall/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
    return getattr(module, func_name)(args, parser)
  File "/Users/stephaniehall/miniconda3/lib/python3.7/site-packages/conda/cli/main_create.py", line 41, in execute
    install(args, parser, 'create')
  File "/Users/stephaniehall/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 265, in install
    should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
  File "/Users/stephaniehall/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
    should_retry_solve)
  File "/Users/stephaniehall/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
    force_remove, should_retry_solve)
  File "/Users/stephaniehall/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 262, in solve_final_state
    ssc = self._collect_all_metadata(ssc)
  File "/Users/stephaniehall/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/Users/stephaniehall/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 397, in _collect_all_metadata
    _supplement_index_with_system(virtual_pkg_index)
  File "/Users/stephaniehall/miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 158, in _supplement_index_with_system
    cuda_version = context.cuda_version
  File "/Users/stephaniehall/miniconda3/lib/python3.7/site-packages/conda/_vendor/auxlib/decorators.py", line 268, in new_fget
    cache[inner_attname] = func(self)
  File "/Users/stephaniehall/miniconda3/lib/python3.7/site-packages/conda/common/decorators.py", line 20, in wrapper
    return func(*args, **kwargs)
  File "/Users/stephaniehall/miniconda3/lib/python3.7/site-packages/conda/base/context.py", line 818, in cuda_version
    return cuda_detect()
  File "/Users/stephaniehall/miniconda3/lib/python3.7/site-packages/conda/common/cuda.py", line 37, in cuda_detect
    import ctypes
  File "/Users/stephaniehall/miniconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dlopen(/Users/stephaniehall/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
  Referenced from: /Users/stephaniehall/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/stephaniehall/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1211, in print_unexpected_error_report
    message_builder.append(get_main_info_str(error_report['conda_info']))
  File "/Users/stephaniehall/miniconda3/lib/python3.7/site-packages/conda/cli/main_info.py", line 238, in get_main_info_str
    info_dict['_' + key] = ('\n' + 26 * ' ').join(info_dict[key])
KeyError: 'pkgs_dirs'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/stephaniehall/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/Users/stephaniehall/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/Users/stephaniehall/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/Users/stephaniehall/miniconda3/lib/python3.7/site-packages/conda/cli/main_create.py", line 41, in execute
        install(args, parser, 'create')
      File "/Users/stephaniehall/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 265, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "/Users/stephaniehall/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "/Users/stephaniehall/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "/Users/stephaniehall/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 262, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/Users/stephaniehall/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/Users/stephaniehall/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 397, in _collect_all_metadata
        _supplement_index_with_system(virtual_pkg_index)
      File "/Users/stephaniehall/miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 158, in _supplement_index_with_system
        cuda_version = context.cuda_version
      File "/Users/stephaniehall/miniconda3/lib/python3.7/site-packages/conda/_vendor/auxlib/decorators.py", line 268, in new_fget
        cache[inner_attname] = func(self)
      File "/Users/stephaniehall/miniconda3/lib/python3.7/site-packages/conda/common/decorators.py", line 20, in wrapper
        return func(*args, **kwargs)
      File "/Users/stephaniehall/miniconda3/lib/python3.7/site-packages/conda/base/context.py", line 818, in cuda_version
        return cuda_detect()
      File "/Users/stephaniehall/miniconda3/lib/python3.7/site-packages/conda/common/cuda.py", line 37, in cuda_detect
        import ctypes
      File "/Users/stephaniehall/miniconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: dlopen(/Users/stephaniehall/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
      Referenced from: /Users/stephaniehall/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
      Reason: image not found

`$ /Users/stephaniehall/miniconda3/bin/conda create -y --name bioinfo python=3.6`

  environment variables:
conda info could not be constructed.
KeyError('pkgs_dirs')

An unexpected error has occurred. Conda has prepared the above report.

Upload successful.
(base) 

I can still do some of the work but I'm concerned that some of the tools are not working properly. Any help with this would be greatly appreciated. 

Thanks

Stephanie

**Comment by ialbert** [comment]
the first error was caused because you have not activated the bioinfo environment, had you done

    conda activate bioinfo

I believe it would worked. Now in the second steps, you need to type commands one a time, then report the error at the command that fails. It is not so easy to troubleshoot this.

perhaps the best would be to deleted your miniconda3 directory and start again from scratch.

**Comment by stephaniehall123** [comment]
Good morning,
Thank you for your quick response. I ended up deleting miniconda3 like you recommended and reinstalling it and now the wget tool and Conda is working again.

Thanks again!
Stephanie
