### ISSUE TITLE
install software: run a realistic analysis

### ISSUE THREAD

**Issue by akgreat22** [biostars/biostar-handbook-issues#243]
After I did conda activate bioinfo, I did this;
doctor.py
# Doctor! Doctor! Give me the news.
# Checking symptoms ...
# bwa ... OK
# datamash ... OK
# fastqc -h ... OK
# hisat2 ... OK
# seqret -h ... OK
# featureCounts ... OK
# efetch ... OK
# esearch ... OK
# samtools ... OK
# fastq-dump ... OK
# bowtie2 ... OK
# bcftools ... OK
# seqtk ... OK
# seqkit ... OK
# bio ... Traceback (most recent call last):
  File "/home/davo/bin/doctor.py", line 125, in <module>
    health_check()
  File "/home/davo/bin/doctor.py", line 105, in health_check
    errors += tool_check(tools=TOOLS)
  File "/home/davo/bin/doctor.py", line 69, in tool_check
    res = subprocess.run(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/home/davo/miniconda3/envs/bioinfo/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/davo/miniconda3/envs/bioinfo/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/home/davo/miniconda3/envs/bioinfo/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'bio': 'bio'
(bioinfo)

Since the bio seem to failed I decided to use "pip install bio --upgrade"
I got a warning: the scripts f2py,, f2py3 and f2py3.8 are installed in '/home/davo/. local/bin hich is not on path
consider adding this directory to path. the same thing goes for "tqdm", "bio" and fasta_filter.py

when I now ran a realistic  analysis ith make command I got
 make
Makefile:61: *** "Program: bio not found.".  Stop.
(bioinfo)
Please kindly help.

**Comment by ialbert** [comment]
the problem seems to be that you have python 3.6 installed

the install script should install python3.8 by default, so that needs to change, perhaps you are using an old version of the book
