### ISSUE TITLE
Unable to install 'bio' package

### ISSUE THREAD

**Issue by LiSun92** [biostars/biostar-handbook-issues#286]
Hey guys;
            So I'm pretty new to bioinformatics, just trying to install biostar handbook as instructed (windows system, ubuntu 22.04). The automatic installation consistently fails at step 6/10 (bio installation), so I tried the step-by-step method; the same error occurs at the bio stage. I'm in China if that helps, tends to do funny things to net connections. Already tried doing this with VPN on/off.

$ pip install bio --upgrade
Collecting bio
  Using cached bio-1.5.9-py3-none-any.whl (276 kB)
Collecting biopython>=1.80 (from bio)
  Downloading biopython-1.81-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
     ━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.2/3.1 MB 14.5 kB/s eta 0:03:22
ERROR: Exception:
Traceback (most recent call last):
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/http/client.py", line 459, in read
    n = self.readinto(b)
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/http/client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 427, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 239, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 230, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
    return bool(self._sequence)
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 293, in __init__
    super().__init__(
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 538, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 609, in _prepare_linked_requirement
    local_file = unpack_url(
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 166, in unpack_url
    file = get_http_url(
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 107, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/site-packages/pip/_internal/network/download.py", line 147, in __call__
    for chunk in chunks:
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/site-packages/pip/_internal/cli/progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 587, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/biouser/micromamba/envs/bioinfo/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

**Comment by LiSun92** [comment]
Nevermind! By setting pip to one of the domestic pypi mirrors, I've solved the issue!

**Comment by kw45382** [comment]
> Nevermind! By setting pip to one of the domestic pypi mirrors, I've solved the issue!

Seemingly insignificant information is a real help, thank you, bro!
